
import React, { useState, useEffect } from 'react';
import Editor from '@monaco-editor/react';
import { generateFullStackProject, convertToColabNotebook } from './services/geminiService';
import { deployToVercel } from './services/vercelService';
import { GitHubService } from './services/githubService';
import { GCSService } from './services/gcsService';
import { COMPONENT_LIBRARY } from './services/library';
import { NeuralModal, ModalTransition } from './components/NeuralModal';
import { PLUGIN_REGISTRY, getActiveInstructions } from './services/extensionService';
import { GeneratedFile, TabType, DeploymentStatus, ModelConfig, Extension } from './types';

const INITIAL_SYSTEM = `你是一个顶级进化级全栈 AI 编排 system（IntelliBuild Studio Core）。`;

const App: React.FC = () => {
  const [modelConfig, setModelConfig] = useState<ModelConfig>({
    temperature: 0.7,
    topP: 0.95,
    topK: 40,
    thinkingBudget: 0,
    systemInstruction: INITIAL_SYSTEM
  });

  const [extensions, setExtensions] = useState<Extension[]>(PLUGIN_REGISTRY);
  const [modalTransition, setModalTransition] = useState<ModalTransition>('slide');
  const [input, setInput] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [currentFiles, setCurrentFiles] = useState<GeneratedFile[]>([]);
  const [selectedFileIndex, setSelectedFileIndex] = useState(0);
  const [activeTab, setActiveTab] = useState<TabType>(TabType.WORKSPACE);
  const [agentLogs, setAgentLogs] = useState<any[]>([]);
  
  // Vercel Credentials
  const [vercelToken, setVercelToken] = useState('');
  
  // GitHub Credentials
  const [githubToken, setGithubToken] = useState('');
  const [githubOwner, setGithubOwner] = useState('');
  const [githubRepoName, setGithubRepoName] = useState('');
  const [githubIsPrivate, setGithubIsPrivate] = useState(true);
  const [githubInitReadme, setGithubInitReadme] = useState(true);
  const [githubStatus, setGithubStatus] = useState<string>('');
  const [githubRepoUrl, setGithubRepoUrl] = useState<string | null>(null);

  // GCS Credentials
  const [gcsToken, setGcsToken] = useState('');
  const [gcsProjectId, setGcsProjectId] = useState('');
  const [gcsBucket, setGcsBucket] = useState('');
  const [gcsBucketsList, setGcsBucketsList] = useState<any[]>([]);
  const [gcsStatus, setGcsStatus] = useState<string>('');

  const [projectName, setProjectName] = useState('studio-export-' + Math.floor(Math.random() * 1000));
  const [deployment, setDeployment] = useState<DeploymentStatus | null>(null);
  const [showInfoModal, setShowInfoModal] = useState(false);

  const toggleExtension = (id: string) => {
    setExtensions(prev => prev.map(ext => 
      ext.id === id ? { ...ext, enabled: !ext.enabled } : ext
    ));
  };

  const handleRun = async () => {
    if (!input.trim()) return;
    setIsGenerating(true);
    setAgentLogs([]);
    
    const pluginAugmentation = getActiveInstructions(extensions);
    const augmentedConfig = {
      ...modelConfig,
      systemInstruction: `${modelConfig.systemInstruction}\n\nACTIVE PLUGINS:\n${pluginAugmentation}`
    };

    try {
      const result = await generateFullStackProject(input, augmentedConfig, COMPONENT_LIBRARY);
      setCurrentFiles(result.files);
      setAgentLogs(result.agentLogs);
      setProjectName(result.projectName || projectName);
      setGithubRepoName(result.projectName || projectName);
      setSelectedFileIndex(0);
      setActiveTab(TabType.EDITOR);
    } catch (e: any) {
      alert("Studio Protocol Error: " + e.message);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleCopyCode = () => {
    const code = currentFiles[selectedFileIndex]?.content;
    if (code) {
      navigator.clipboard.writeText(code);
      alert('Code copied to clipboard!');
    }
  };

  const handleGitHubPush = async () => {
    if (!githubToken || !githubRepoName || !githubOwner) {
      return alert('GitHub Token, Owner, and Repo Name are required');
    }
    if (currentFiles.length === 0) {
      return alert('No code generated yet to push.');
    }

    setIsGenerating(true);
    setGithubStatus('Initializing GitHub Handshake...');
    
    try {
      const service = new GitHubService(githubToken);
      
      setGithubStatus(`Creating repository: ${githubRepoName}...`);
      await service.createRepository(githubRepoName, githubIsPrivate);
      
      const filesToPush = [...currentFiles];
      if (githubInitReadme) {
        filesToPush.push({
          path: 'README.md',
          content: `# ${githubRepoName}\n\nGenerated by IntelliBuild Studio.\n\n## Project Description\n${input}`,
          type: 'config'
        });
      }

      setGithubStatus(`Pushing ${filesToPush.length} files to master...`);
      await service.initializeAndPush(githubOwner, githubRepoName, filesToPush);
      
      const url = `https://github.com/${githubOwner}/${githubRepoName}`;
      setGithubRepoUrl(url);
      setGithubStatus('Push Successful!');
    } catch (err: any) {
      setGithubStatus(`Error: ${err.message}`);
      alert(err.message);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleExportColab = () => {
    if (currentFiles.length === 0) {
      alert("No files to export. Please build a project first.");
      return;
    }
    const notebookJson = convertToColabNotebook(currentFiles, projectName);
    const blob = new Blob([notebookJson], { type: 'application/x-ipynb+json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${projectName}.ipynb`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleGCSFetchBuckets = async () => {
    if (!gcsToken || !gcsProjectId) return alert('Token and Project ID required');
    try {
      setGcsStatus('Fetching buckets...');
      const service = new GCSService(gcsToken);
      const buckets = await service.listBuckets(gcsProjectId);
      setGcsBucketsList(buckets);
      setGcsStatus('Buckets loaded.');
    } catch (err: any) {
      alert(err.message);
      setGcsStatus('Fetch failed.');
    }
  };

  const handleGCSUpload = async () => {
    if (!gcsToken || !gcsBucket || currentFiles.length === 0) return alert('Token, Bucket, and Files required');
    try {
      setIsGenerating(true);
      setGcsStatus('Uploading files...');
      const service = new GCSService(gcsToken);
      await service.uploadProject(gcsBucket, currentFiles, projectName);
      setGcsStatus('Upload successful!');
    } catch (err: any) {
      alert(err.message);
      setGcsStatus('Upload failed.');
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="flex h-screen bg-[#0E0E0E] text-[#E3E3E3] font-sans overflow-hidden">
      {/* Sidebar navigation */}
      <aside className="w-64 border-r border-[#303030] flex flex-col bg-[#111111]">
        <div className="p-4 border-b border-[#303030] flex items-center justify-between">
          <span className="font-bold text-xs tracking-widest text-blue-400">INTELLIBUILD STUDIO</span>
        </div>
        <div className="flex-1 overflow-y-auto p-2">
          <div className="space-y-1">
            <div className="px-3 py-2 text-[10px] font-bold text-[#555] uppercase tracking-tighter">Workflow</div>
            <NavButton active={activeTab === TabType.WORKSPACE} onClick={() => setActiveTab(TabType.WORKSPACE)} label="Compiler" icon="⚡" />
            <NavButton active={activeTab === TabType.EDITOR} onClick={() => setActiveTab(TabType.EDITOR)} label="Source Code" icon="📁" />
            <NavButton active={activeTab === TabType.PLUGINS} onClick={() => setActiveTab(TabType.PLUGINS)} label="Plugin Depot" icon="🧩" />
            <NavButton active={activeTab === TabType.DEPLOY} onClick={() => setActiveTab(TabType.DEPLOY)} label="Deployment" icon="🚀" />
            <NavButton active={activeTab === TabType.GCS} onClick={() => setActiveTab(TabType.GCS)} label="Cloud Storage" icon="☁️" />
            
            <div className="pt-4 px-3 py-2 text-[10px] font-bold text-[#555] uppercase tracking-tighter">Tools</div>
            <NavButton active={activeTab === TabType.COLAB} onClick={() => setActiveTab(TabType.COLAB)} label="Colab Lab" icon="📙" />
            <NavButton active={false} onClick={() => setShowInfoModal(true)} label="Studio Info" icon="ⓘ" />
          </div>
        </div>
        <div className="p-4 border-t border-[#303030]">
          <div className="flex items-center space-x-3 text-[10px] opacity-60 font-mono">
            <div className={`w-1.5 h-1.5 rounded-full ${isGenerating ? 'bg-orange-500 animate-pulse' : 'bg-green-500'}`}></div>
            <span>{isGenerating ? 'PROCESSING' : 'STABLE'}</span>
          </div>
        </div>
      </aside>

      {/* Primary Workspace */}
      <main className="flex-1 flex flex-col min-w-0">
        <header className="h-14 border-b border-[#303030] flex items-center px-6 justify-between bg-[#111111]">
          <div className="flex space-x-8 h-full">
            <TabButton active={activeTab === TabType.WORKSPACE} onClick={() => setActiveTab(TabType.WORKSPACE)} label="Build" />
            <TabButton active={activeTab === TabType.EDITOR} onClick={() => setActiveTab(TabType.EDITOR)} label="Inspect" />
            <TabButton active={activeTab === TabType.PLUGINS} onClick={() => setActiveTab(TabType.PLUGINS)} label="Depot" />
            <TabButton active={activeTab === TabType.LOGS} onClick={() => setActiveTab(TabType.LOGS)} label="Telemetry" />
          </div>
          <div className="flex items-center space-x-4">
             {activeTab === TabType.WORKSPACE && (
               <button onClick={handleRun} disabled={isGenerating} className="px-6 py-1.5 bg-blue-600 hover:bg-blue-500 disabled:opacity-50 text-white font-bold text-xs rounded-full transition-all shadow-[0_0_15px_rgba(37,99,235,0.3)] active:scale-95">
                  {isGenerating ? 'GENERATING...' : 'INITIATE COMPILATION'}
               </button>
             )}
          </div>
        </header>

        <div className="flex-1 relative flex flex-col bg-[#0F0F0F] overflow-hidden">
          {activeTab === TabType.WORKSPACE && (
            <div className="h-full flex flex-col">
               <div className="p-6 border-b border-[#303030] bg-[#111111]/50">
                  <div className="flex items-center justify-between mb-2">
                    <label className="text-[10px] font-bold text-blue-400 uppercase tracking-widest">Protocol Instruction</label>
                  </div>
                  <textarea 
                    value={modelConfig.systemInstruction}
                    onChange={e => setModelConfig({...modelConfig, systemInstruction: e.target.value})}
                    className="w-full bg-black/40 border border-[#303030] rounded-xl p-4 text-sm focus:border-blue-500 outline-none min-h-[100px] resize-none font-mono leading-relaxed"
                  />
               </div>
               <div className="flex-1 p-8 flex flex-col">
                  <div className="flex-1 flex flex-col glass-panel rounded-2xl p-6 border border-white/5 shadow-inner">
                    <label className="block text-[10px] font-bold text-[#9CA3AF] uppercase mb-4 tracking-widest">Compiler Prompt</label>
                    <textarea 
                      value={input}
                      onChange={e => setInput(e.target.value)}
                      className="flex-1 w-full bg-transparent text-2xl font-extralight focus:outline-none resize-none leading-relaxed placeholder:text-white/10"
                      placeholder="e.g., Build a real-time data visualization dashboard..."
                    />
                  </div>
               </div>
            </div>
          )}

          {activeTab === TabType.PLUGINS && (
            <div className="h-full p-12 bg-[#0E0E0E] overflow-y-auto custom-scrollbar">
              <div className="max-w-5xl mx-auto space-y-10">
                <header>
                  <h1 className="text-3xl font-extrabold text-white tracking-tight">Plugin Depot</h1>
                  <p className="text-white/40 mt-2">Dynamic sub-systems for the Studio inference engine.</p>
                </header>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {extensions.map(ext => (
                    <div key={ext.id} className={`p-6 border rounded-2xl transition-all duration-300 ${ext.enabled ? 'bg-blue-600/5 border-blue-500/30' : 'bg-white/2 border-white/5 opacity-60'}`}>
                      <div className="flex justify-between items-start mb-4">
                        <div className="space-y-1">
                          <span className={`text-[9px] font-bold px-2 py-0.5 rounded uppercase ${ext.enabled ? 'bg-blue-400 text-blue-900' : 'bg-white/10 text-white/50'}`}>
                            {ext.category}
                          </span>
                          <h3 className="text-lg font-bold text-white">{ext.name}</h3>
                          <p className="text-xs text-white/50">{ext.description}</p>
                        </div>
                        <button 
                          onClick={() => toggleExtension(ext.id)}
                          className={`w-12 h-6 rounded-full relative transition-all duration-500 ${ext.enabled ? 'bg-blue-500' : 'bg-[#303030]'}`}
                        >
                          <div className={`absolute top-1 w-4 h-4 rounded-full bg-white transition-all duration-300 ${ext.enabled ? 'left-7' : 'left-1'}`} />
                        </button>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {activeTab === TabType.EDITOR && (
            <div className="h-full flex">
              <div className="w-56 border-r border-[#303030] bg-[#111111] overflow-y-auto">
                <div className="p-4 border-b border-[#303030] text-[10px] font-bold text-[#555] uppercase tracking-tighter">Project Files</div>
                {currentFiles.map((f, i) => (
                  <button key={i} onClick={() => setSelectedFileIndex(i)} className={`w-full text-left px-4 py-3 text-xs truncate transition-all ${selectedFileIndex === i ? 'bg-[#1C1C1C] text-blue-400 border-r-2 border-blue-400' : 'text-[#888] hover:bg-[#161616]'}`}>
                    {f.path.split('/').pop()}
                  </button>
                ))}
              </div>
              <div className="flex-1 relative group">
                <Editor height="100%" theme="vs-dark" defaultLanguage="typescript" value={currentFiles[selectedFileIndex]?.content || ""} options={{ fontSize: 13, minimap: { enabled: false } }} />
                <div className="absolute top-4 right-8 opacity-0 group-hover:opacity-100 transition-opacity">
                   <button onClick={handleCopyCode} className="px-3 py-1.5 bg-black/50 backdrop-blur border border-white/10 rounded-md text-[10px] font-bold text-white/60 hover:text-white uppercase tracking-widest flex items-center space-x-2">
                      <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg>
                      <span>Copy Snippet</span>
                   </button>
                </div>
              </div>
            </div>
          )}

          {activeTab === TabType.LOGS && (
            <div className="p-8 h-full overflow-y-auto font-mono text-xs">
              <h2 className="text-sm font-bold mb-4 text-blue-400 uppercase tracking-widest">Telemetric Flow Log</h2>
              <div className="space-y-3">
                <div className="flex space-x-4 border-l-2 border-green-500/30 pl-4 py-2 bg-green-500/5 rounded-r-md">
                  <span className="text-green-500 font-bold w-24 uppercase">[SYSTEM]</span>
                  <span className="text-[#D1D5DB]">Studio system ready. Plugins synced.</span>
                </div>
                {agentLogs.map((log, i) => (
                  <div key={i} className="flex space-x-4 border-l-2 border-[#303030] pl-4 py-2">
                    <span className="text-[#9CA3AF] w-24">[{log.agent.toUpperCase()}]</span>
                    <span className="text-[#D1D5DB]">{log.action}</span>
                    <span className={`text-[9px] px-2 py-0.5 rounded ${log.status === 'complete' ? 'bg-green-900/40 text-green-400' : 'bg-blue-900/40 text-blue-400'}`}>
                      {log.status.toUpperCase()}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {activeTab === TabType.COLAB && (
            <div className="h-full p-12 bg-[#0E0E0E] flex flex-col items-center justify-center space-y-8 text-center">
              <div className="w-20 h-20 bg-orange-500/10 rounded-3xl flex items-center justify-center text-4xl border border-orange-500/20">
                📙
              </div>
              <div className="max-w-md space-y-3">
                <h2 className="text-2xl font-bold text-white tracking-tight">Export to Google Colab</h2>
                <p className="text-white/50 text-sm leading-relaxed">
                  Convert your generated project files into a single Jupyter Notebook (.ipynb) compatible with Google Colab.
                </p>
              </div>
              <button onClick={handleExportColab} disabled={currentFiles.length === 0} className="px-10 py-4 bg-orange-600 hover:bg-orange-500 disabled:opacity-30 text-white font-bold rounded-2xl transition-all shadow-xl active:scale-95 text-xs uppercase tracking-widest">
                Download Notebook (.ipynb)
              </button>
            </div>
          )}

          {activeTab === TabType.DEPLOY && (
            <div className="h-full grid grid-cols-1 md:grid-cols-2 gap-8 p-12 overflow-y-auto bg-[#0E0E0E] custom-scrollbar">
              {/* Vercel Section */}
              <div className="border border-[#303030] rounded-3xl p-8 bg-[#141414] shadow-2xl flex flex-col">
                 <h2 className="text-xl font-bold flex items-center space-x-2 text-white mb-2"><span>▲</span> <span>Vercel Edge</span></h2>
                 <p className="text-xs text-[#9CA3AF] mb-8 font-medium">Instantly deploy to global infrastructure.</p>
                 <div className="space-y-5 flex-1">
                    <div>
                      <label className="text-[10px] font-bold uppercase tracking-widest text-[#555]">Vercel API Token</label>
                      <input 
                        type="password" 
                        value={vercelToken} 
                        onChange={e => setVercelToken(e.target.value)} 
                        className="w-full bg-[#0E0E0E] border border-[#303030] rounded-xl p-3 text-sm mt-1 focus:ring-1 ring-blue-500 outline-none transition-all placeholder:text-[#333]" 
                        placeholder="sk_..." 
                      />
                    </div>
                 </div>
                 <div className="mt-8 space-y-4">
                   <button 
                     onClick={async () => {
                       if (!vercelToken) return alert('Token required');
                       setIsGenerating(true);
                       try {
                         const d = await deployToVercel(currentFiles, vercelToken, projectName);
                         setDeployment(d);
                       } catch (err: any) { alert(err.message); } finally { setIsGenerating(false); }
                     }} 
                     className="w-full py-4 bg-white text-black font-bold rounded-2xl hover:bg-gray-100 transition-all text-xs uppercase tracking-widest shadow-lg active:scale-95 disabled:opacity-50"
                     disabled={isGenerating}
                   >
                     Launch to Vercel
                   </button>
                   {deployment && (
                     <div className="p-4 bg-green-500/5 border border-green-500/20 rounded-2xl text-xs">
                        <div className="flex justify-between items-center mb-2">
                          <span className="text-[#555] font-bold uppercase tracking-widest">Status</span>
                          <span className="text-green-400 font-bold">{deployment.state}</span>
                        </div>
                        <a href={`https://${deployment.url}`} target="_blank" className="w-full block py-2 text-center bg-blue-500/10 text-blue-400 rounded-xl border border-blue-500/20 hover:bg-blue-500/20 transition-all font-bold mt-2">Open Deployment →</a>
                     </div>
                   )}
                 </div>
              </div>

              {/* GitHub Section */}
              <div className="border border-[#303030] rounded-3xl p-8 bg-[#141414] shadow-2xl flex flex-col">
                 <h2 className="text-xl font-bold flex items-center space-x-2 text-white mb-2">
                   <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
                   <span>GitHub Pipeline</span>
                 </h2>
                 <p className="text-xs text-[#9CA3AF] mb-8 font-medium">Commit and push to your repositories.</p>
                 <div className="space-y-4 flex-1">
                    <div>
                      <label className="text-[10px] font-bold uppercase tracking-widest text-[#555]">Personal Access Token</label>
                      <input 
                        type="password" 
                        value={githubToken} 
                        onChange={e => setGithubToken(e.target.value)} 
                        className="w-full bg-[#0E0E0E] border border-[#303030] rounded-xl p-3 text-sm mt-1 focus:ring-1 ring-blue-500 outline-none transition-all placeholder:text-[#333]" 
                        placeholder="ghp_..." 
                      />
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <label className="text-[10px] font-bold uppercase tracking-widest text-[#555]">Owner / Username</label>
                        <input 
                          type="text" 
                          value={githubOwner} 
                          onChange={e => setGithubOwner(e.target.value)} 
                          className="w-full bg-[#0E0E0E] border border-[#303030] rounded-xl p-3 text-sm mt-1 focus:ring-1 ring-blue-500 outline-none transition-all placeholder:text-[#333]" 
                          placeholder="octocat" 
                        />
                      </div>
                      <div>
                        <label className="text-[10px] font-bold uppercase tracking-widest text-[#555]">Repository Name</label>
                        <input 
                          type="text" 
                          value={githubRepoName} 
                          onChange={e => setGithubRepoName(e.target.value)} 
                          className="w-full bg-[#0E0E0E] border border-[#303030] rounded-xl p-3 text-sm mt-1 focus:ring-1 ring-blue-500 outline-none transition-all placeholder:text-[#333]" 
                          placeholder="my-cool-project" 
                        />
                      </div>
                    </div>
                    <div className="flex items-center space-x-6 pt-2">
                      <label className="flex items-center space-x-2 cursor-pointer group">
                        <input type="checkbox" checked={githubIsPrivate} onChange={e => setGithubIsPrivate(e.target.checked)} className="hidden" />
                        <div className={`w-4 h-4 rounded border ${githubIsPrivate ? 'bg-blue-600 border-blue-600' : 'border-[#444]'} flex items-center justify-center transition-all`}>
                          {githubIsPrivate && <svg width="10" height="10" viewBox="0 0 24 24" fill="white"><path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"/></svg>}
                        </div>
                        <span className="text-[10px] font-bold uppercase text-[#888] group-hover:text-white transition-colors">Private Repo</span>
                      </label>
                      <label className="flex items-center space-x-2 cursor-pointer group">
                        <input type="checkbox" checked={githubInitReadme} onChange={e => setGithubInitReadme(e.target.checked)} className="hidden" />
                        <div className={`w-4 h-4 rounded border ${githubInitReadme ? 'bg-blue-600 border-blue-600' : 'border-[#444]'} flex items-center justify-center transition-all`}>
                          {githubInitReadme && <svg width="10" height="10" viewBox="0 0 24 24" fill="white"><path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"/></svg>}
                        </div>
                        <span className="text-[10px] font-bold uppercase text-[#888] group-hover:text-white transition-colors">Init README</span>
                      </label>
                    </div>
                 </div>
                 <div className="mt-8 space-y-4">
                   <button 
                     onClick={handleGitHubPush} 
                     className="w-full py-4 bg-[#2EA44F] text-white font-bold rounded-2xl hover:bg-[#2C974B] transition-all text-xs uppercase tracking-widest shadow-lg active:scale-95 disabled:opacity-50"
                     disabled={isGenerating}
                   >
                     {isGenerating ? 'Pushing...' : 'Initialize & Sync GitHub'}
                   </button>
                   {githubStatus && (
                     <div className="p-4 bg-white/5 border border-white/10 rounded-2xl text-[10px] font-mono">
                        <div className="flex justify-between items-center mb-1">
                          <span className="text-[#555] uppercase font-bold">Protocol Status</span>
                        </div>
                        <span className="text-white/70 block truncate">{githubStatus}</span>
                        {githubRepoUrl && (
                          <a href={githubRepoUrl} target="_blank" className="text-blue-400 mt-2 block underline">Visit Repository →</a>
                        )}
                     </div>
                   )}
                 </div>
              </div>
            </div>
          )}

          {activeTab === TabType.GCS && (
            <div className="h-full p-12 bg-[#0E0E0E] overflow-y-auto custom-scrollbar">
              <div className="max-w-4xl mx-auto space-y-8">
                <header className="flex items-center space-x-4">
                  <div className="w-12 h-12 bg-blue-500/20 rounded-2xl flex items-center justify-center text-2xl border border-blue-500/30">☁️</div>
                  <div>
                    <h1 className="text-2xl font-extrabold text-white">Google Cloud Storage</h1>
                    <p className="text-white/40 text-sm">Upload and manage project assets in GCS buckets.</p>
                  </div>
                </header>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                  <div className="glass-panel p-8 rounded-3xl border border-white/5 space-y-6">
                    <h3 className="text-xs font-bold text-blue-400 uppercase tracking-widest">Configuration</h3>
                    
                    <div className="space-y-4">
                      <div>
                        <label className="text-[10px] font-bold uppercase tracking-widest text-[#555]">Access Token (OAuth2)</label>
                        <input 
                          type="password" 
                          value={gcsToken} 
                          onChange={e => setGcsToken(e.target.value)} 
                          className="w-full bg-[#0E0E0E] border border-[#303030] rounded-xl p-3 text-sm focus:ring-1 ring-blue-500 outline-none" 
                          placeholder="ya29.a0AfH..."
                        />
                      </div>
                      <div>
                        <label className="text-[10px] font-bold uppercase tracking-widest text-[#555]">Project ID</label>
                        <div className="flex gap-2">
                          <input 
                            type="text" 
                            value={gcsProjectId} 
                            onChange={e => setGcsProjectId(e.target.value)} 
                            className="flex-1 bg-[#0E0E0E] border border-[#303030] rounded-xl p-3 text-sm focus:ring-1 ring-blue-500 outline-none" 
                            placeholder="my-project-123"
                          />
                          <button onClick={handleGCSFetchBuckets} className="px-4 bg-white/5 border border-white/10 rounded-xl hover:bg-white/10 transition-all text-[10px] font-bold uppercase">Fetch</button>
                        </div>
                      </div>
                      <div>
                        <label className="text-[10px] font-bold uppercase tracking-widest text-[#555]">Select Bucket</label>
                        <select 
                          value={gcsBucket} 
                          onChange={e => setGcsBucket(e.target.value)}
                          className="w-full bg-[#0E0E0E] border border-[#303030] rounded-xl p-3 text-sm focus:ring-1 ring-blue-500 outline-none text-white font-mono"
                        >
                          <option value="">Choose a bucket...</option>
                          {gcsBucketsList.map(b => (
                            <option key={b.id} value={b.name}>{b.name}</option>
                          ))}
                        </select>
                      </div>
                    </div>
                  </div>

                  <div className="glass-panel p-8 rounded-3xl border border-white/5 flex flex-col justify-between">
                    <div>
                      <h3 className="text-xs font-bold text-blue-400 uppercase tracking-widest mb-4">Action</h3>
                      <p className="text-xs text-white/50 leading-relaxed mb-6">
                        Upload all currently generated files to the selected bucket. 
                        Files will be stored under a folder named after your project: <span className="text-blue-400 font-mono">/{projectName}</span>
                      </p>
                      
                      {gcsStatus && (
                        <div className="mb-6 p-4 bg-blue-500/5 border border-blue-500/10 rounded-xl">
                          <span className="text-[10px] font-bold text-blue-400 uppercase tracking-widest block mb-1">Status Report</span>
                          <span className="text-xs font-mono">{gcsStatus}</span>
                        </div>
                      )}
                    </div>

                    <button 
                      onClick={handleGCSUpload}
                      disabled={!gcsToken || !gcsBucket || currentFiles.length === 0 || isGenerating}
                      className="w-full py-4 bg-blue-600 hover:bg-blue-500 disabled:opacity-30 text-white font-bold rounded-2xl transition-all shadow-xl active:scale-95 text-xs uppercase tracking-widest"
                    >
                      {isGenerating ? 'Processing...' : 'Upload Project to GCS'}
                    </button>
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
      </main>

      {/* Right control panel */}
      <aside className="w-72 border-l border-[#303030] bg-[#111111] flex flex-col p-6 space-y-8">
        <div className="space-y-4">
          <h3 className="text-[10px] font-bold text-blue-400 uppercase tracking-widest border-b border-[#262626] pb-2">Configuration</h3>
          <div>
            <label className="text-[11px] mb-2 uppercase font-bold text-[#888]">Compiler</label>
            <select className="w-full bg-[#0E0E0E] border border-[#303030] rounded p-2 text-xs outline-none focus:border-blue-500 text-white font-mono">
               <option>gemini-3-pro-preview</option>
               <option>gemini-3-flash-preview</option>
            </select>
          </div>
          <div>
            <label className="text-[11px] mb-2 uppercase font-bold text-[#888]">Modal Animation</label>
            <select 
              value={modalTransition}
              onChange={(e) => setModalTransition(e.target.value as ModalTransition)}
              className="w-full bg-[#0E0E0E] border border-[#303030] rounded p-2 text-xs outline-none focus:border-blue-500 text-white"
            >
               <option value="zoom">Zoom (Standard)</option>
               <option value="slide">Slide (Vertical)</option>
               <option value="fade">Fade (Ghost)</option>
               <option value="fadeSlideIn">Fade + Slide (Subtle)</option>
            </select>
          </div>
        </div>
        
        <div className="flex-1"></div>
        
        <div className="p-4 bg-blue-500/5 border border-blue-500/10 rounded-2xl space-y-3">
           <p className="text-[10px] font-bold text-blue-400 uppercase tracking-widest">Neural UI Stack</p>
           <p className="text-[11px] text-[#9CA3AF] leading-relaxed">
             Active Files: {currentFiles.length}
           </p>
           <div className="flex flex-wrap gap-1 pt-1">
             {currentFiles.slice(0, 3).map((f, idx) => (
               <span key={idx} className="px-2 py-0.5 bg-blue-900/40 text-blue-400 text-[8px] font-bold rounded uppercase truncate max-w-[80px]">{f.path.split('/').pop()}</span>
             ))}
             {currentFiles.length > 3 && <span className="text-[8px] text-white/30 font-bold">+{currentFiles.length - 3}</span>}
           </div>
        </div>
      </aside>

      <NeuralModal 
        isOpen={showInfoModal} 
        onClose={() => setShowInfoModal(false)} 
        title="Studio Protocol Information" 
        transition={modalTransition}
        content={
          <div className="space-y-4">
            <p className="text-white/70 text-sm">Protocol Core: IntelliBuild AI v4.0.2</p>
            <p className="text-white/40 text-xs">Current transition set to: <span className="text-blue-400 font-mono">{modalTransition}</span></p>
            <div className="pt-4 border-t border-white/5 space-y-2">
               <p className="text-[10px] font-bold text-white/40 uppercase">System Integrity</p>
               <div className="grid grid-cols-2 gap-2 text-[10px]">
                 <div className="flex justify-between border border-white/5 p-2 rounded"><span>latency</span> <span className="text-green-500">24ms</span></div>
                 <div className="flex justify-between border border-white/5 p-2 rounded"><span>status</span> <span className="text-green-500">verified</span></div>
               </div>
            </div>
          </div>
        } 
      />
    </div>
  );
};

const TabButton: React.FC<{ active: boolean; onClick: () => void; label: string }> = ({ active, onClick, label }) => (
  <button onClick={onClick} className={`h-full text-[10px] font-bold uppercase tracking-widest px-6 border-b-2 transition-all ${active ? 'border-blue-400 text-blue-400 bg-blue-400/5' : 'border-transparent text-[#555] hover:text-[#999]'}`}>
    {label}
  </button>
);

const NavButton: React.FC<{ active: boolean; onClick: () => void; label: string; icon: string }> = ({ active, onClick, label, icon }) => (
  <button onClick={onClick} className={`w-full flex items-center space-x-3 px-4 py-3 rounded-xl transition-all ${active ? 'bg-white/5 text-white border border-white/10' : 'text-white/40 hover:bg-white/5 hover:text-white'}`}>
    <span className="text-base">{icon}</span>
    <span className="text-xs font-medium uppercase tracking-widest">{label}</span>
  </button>
);

export default App;
