
import { GoogleGenAI, Type } from "@google/genai";
import { GenerationResult, LibraryItem, ModelConfig, GeneratedFile } from "../types";

const DEFAULT_SYSTEM_INSTRUCTION = `你是一个顶级进化级全栈 AI 编排系统（IntelliBuild Studio Core）。
你的核心开发准则是：
1. 【极致无障碍 (Accessibility)】：必须使用语义化 HTML5 标签。所有交互组件必须包含完整的 WAI-ARIA 属性。
2. 【现代 SaaS 架构】：参考 ixartz, async-labs 等顶级 SaaS 模板的目录结构。确保代码是模块化、可扩展的。
3. 【数据驱动】：如果提供了 [Knowledge Shard]，必须将其中的数据点集成到 UI 的 Mock 数据或初始状态中。
4. 【性能与美学】：使用 Tailwind CSS。采用“深色奢华 (Luxury Dark)”风格，配合黄金比例布局和微交互。`;

export const generateFullStackProject = async (
  prompt: string, 
  config: ModelConfig,
  customLibrary: LibraryItem[] = [],
  contextShards: string[] = []
): Promise<GenerationResult> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  const libraryContext = customLibrary.map(item => `- ${item.name}: ${item.description}`).join('\n');
  const vaultContext = contextShards.join('\n\n');

  const enhancedPrompt = `User Intent: ${prompt}

Intelligence Vault Context (Integrated Knowledge):
${vaultContext}

Technical Requirements:
- Build a production-grade SaaS shard.
- Follow the structure of modern boilerplates (React/Next.js).
- Include comprehensive ARIA support.
- Provide a Vitest suite (.test.tsx) for core logic.`;

  const genConfig: any = {
    systemInstruction: `${config.systemInstruction || DEFAULT_SYSTEM_INSTRUCTION}\n\nLibrary reuse protocols:\n${libraryContext}`,
    responseMimeType: "application/json",
    temperature: config.temperature,
    topP: config.topP,
    topK: config.topK,
    responseSchema: {
      type: Type.OBJECT,
      properties: {
        projectName: { type: Type.STRING },
        files: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              path: { type: Type.STRING },
              content: { type: Type.STRING },
              type: { type: Type.STRING, description: "frontend | backend | test | config" }
            },
            required: ["path", "content", "type"]
          }
        },
        agentLogs: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              agent: { type: Type.STRING },
              action: { type: Type.STRING },
              status: { type: Type.STRING }
            }
          }
        }
      },
      required: ["projectName", "files", "agentLogs"]
    }
  };

  if (config.thinkingBudget > 0) {
    genConfig.thinkingConfig = { thinkingBudget: config.thinkingBudget };
  }

  const response = await ai.models.generateContent({
    model: config.thinkingBudget > 0 ? "gemini-3-pro-preview" : "gemini-3-flash-preview",
    contents: enhancedPrompt,
    config: genConfig
  });

  return JSON.parse(response.text || '{}') as GenerationResult;
};

// ... remaining service functions (convertColab, generateImagePro, etc) remain unchanged
export const convertToColabNotebook = (files: GeneratedFile[], projectName: string): string => {
  const cells: any[] = [
    {
      cell_type: "markdown",
      metadata: {},
      source: [`# ${projectName}\n`, "Generated by IntelliBuild Studio."]
    }
  ];
  files.forEach(file => {
    cells.push({ cell_type: "markdown", metadata: {}, source: [`## File: \`${file.path}\`\n`] });
    cells.push({ cell_type: "code", execution_count: null, metadata: {}, outputs: [], source: file.content.split('\n').map(line => line + '\n') });
  });
  return JSON.stringify({ cells, metadata: { kernelspec: { display_name: "Python 3", language: "python", name: "python3" }, language_info: { name: "python", version: "3.8" } }, nbformat: 4, nbformat_minor: 0 }, null, 2);
};
