
/**
 * GitHub API Service
 * Handles repository creation, file initialization, and code pushing.
 */
export class GitHubService {
  private baseUrl = 'https://api.github.com';

  constructor(private token: string) {
    if (!token) throw new Error("GitHub Token is required");
  }

  /**
   * Headers for authenticated requests
   */
  private getHeaders() {
    return {
      'Authorization': `token ${this.token}`,
      'Accept': 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
    };
  }

  /**
   * Create a new repository for the authenticated user.
   */
  async createRepository(name: string, isPrivate: boolean = true) {
    const response = await fetch(`${this.baseUrl}/user/repos`, {
      method: 'POST',
      headers: this.getHeaders(),
      body: JSON.stringify({
        name,
        private: isPrivate,
        auto_init: false, // We handle initialization manually to control files
        description: 'Generated by IntelliBuild Studio',
      }),
    });

    if (!response.ok) {
      const error = await response.json();
      throw new Error(`GitHub Create Repo Error: ${error.message || response.statusText}`);
    }

    return response.json();
  }

  /**
   * Upsert a file in a repository.
   * Note: For new repositories, the first push initializes the branch.
   */
  async pushFile(owner: string, repo: string, path: string, content: string, message: string, sha?: string) {
    // Content must be base64 encoded for GitHub API
    const contentBase64 = btoa(unescape(encodeURIComponent(content)));

    const body: any = {
      message,
      content: contentBase64,
    };

    if (sha) {
      body.sha = sha;
    }

    const response = await fetch(`${this.baseUrl}/repos/${owner}/${repo}/contents/${path}`, {
      method: 'PUT',
      headers: this.getHeaders(),
      body: JSON.stringify(body),
    });

    if (!response.ok) {
      const error = await response.json();
      throw new Error(`GitHub Push File Error (${path}): ${error.message || response.statusText}`);
    }

    return response.json();
  }

  /**
   * Initialize a repository with a set of files.
   */
  async initializeAndPush(owner: string, repo: string, files: { path: string; content: string }[]) {
    const results = [];
    for (const file of files) {
      const res = await this.pushFile(owner, repo, file.path, file.content, `Initial commit: ${file.path}`);
      results.push(res);
    }
    return results;
  }
}

/**
 * Unit Tests for GitHubService (Conceptual/Executable in test runner)
 */
export const runGitHubTests = () => {
  console.log("Starting GitHubService Unit Tests...");
  
  // Mocking fetch for testing
  const originalFetch = window.fetch;
  
  try {
    // Test: Token Validation
    try {
      new GitHubService("");
    } catch (e: any) {
      console.assert(e.message === "GitHub Token is required", "Should fail without token");
    }

    console.log("GitHubService tests passed (Conceptual check complete).");
  } finally {
    window.fetch = originalFetch;
  }
};
